# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.CharField(max_length=16, unique=True, verbose_name='\u73ed\u53f7')),
                ('classname', models.CharField(max_length=20, verbose_name='\u73ed\u7ea7\u540d\u79f0')),
            ],
            options={
                'db_table': 'ClassInfo',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begindate', models.DateField(verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('enddate', models.DateField(verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('term', models.CharField(max_length=16, verbose_name='\u5b66\u671f')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='\u540d\u5b57')),
            ],
            options={
                'db_table': 'CourseInfo',
                'verbose_name_plural': '\u4e13\u4e1a\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserMgr.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=40, unique=True)),
                ('role', models.IntegerField(choices=[(0, '\u5b66\u751f'), (1, '\u8001\u5e08'), (2, '\u7ba1\u7406\u5458')])),
                ('realname', models.CharField(max_length=16, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=1, verbose_name='\u6027\u522b')),
                ('course', models.ManyToManyField(blank=True, null=True, to='UserMgr.Course')),
                ('theclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserMgr.Class', verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
