# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('0', '\u7537'), ('1', '\u5973')], max_length=1, verbose_name='\u6027\u522b'),
        ),
    ]
